const reports = [
  { id: 1, category: '급식', title: '오늘 급식에 알레르기 표시가 없어요', content: '메뉴 옆에 알레르기 유발 식품 표시가 빠져 있어서 확인하기 어려웠어요.', place: '본관 급식실', date: '오늘', votes: 84, duplicate: true },
  { id: 2, category: '시설', title: '도서관 3층 콘센트가 작동하지 않아요', content: '창가 쪽 좌석 여러 곳에서 충전이 되지 않습니다. 시험기간이라 불편해요.', place: '도서관 3층', date: '어제', votes: 63, duplicate: true },
  { id: 3, category: '안전', title: '후문 횡단보도 신호 시간이 너무 짧아요', content: '등교 시간에 학생이 많은데 초록불 시간이 짧아서 뛰어 건너는 친구들이 있어요.', place: '학교 후문', date: '2일 전', votes: 47 },
  { id: 4, category: '학습', title: '2학년 5반 빔프로젝터 화면이 흐려요', content: '수업 자료의 글자가 잘 보이지 않아 뒷자리에서 불편합니다.', place: '2학년 5반', date: '3일 전', votes: 29 }
];
let filter = '전체'; let newestFirst = false; let nextId = 5;
const els = { list: document.querySelector('#reportList'), filters: document.querySelector('#filters'), title: document.querySelector('#titleInput'), content: document.querySelector('#contentInput'), analysis: document.querySelector('#aiAnalysis'), form: document.querySelector('#reportForm'), photo: document.querySelector('#photoInput'), fileName: document.querySelector('#fileName'), toast: document.querySelector('#toast') };
const rules = { 급식:['급식','식당','메뉴','밥','음식','알레르기'], 시설:['고장','화장실','콘센트','정수기','에어컨','문','시설'], 학습:['수업','교실','시험','빔','프로젝터','학습','도서관'], 안전:['안전','위험','횡단보도','신호','계단','사고'], 생활:['소음','불편','동아리','휴지','분실','생활'] };
function categorize(text) { const lower = text.toLowerCase(); return Object.entries(rules).map(([key, words]) => [key, words.filter(w => lower.includes(w)).length]).sort((a,b)=>b[1]-a[1])[0][1] ? Object.entries(rules).map(([key, words]) => [key, words.filter(w => lower.includes(w)).length]).sort((a,b)=>b[1]-a[1])[0][0] : '생활'; }
function render() { let items = reports.filter(r => filter === '전체' || r.category === filter); items = [...items].sort((a,b)=> newestFirst ? b.id-a.id : b.votes-a.votes); els.list.innerHTML = items.map(r => `<article class="report-card ${r.duplicate?'duplicate':''}">${r.duplicate?'<span class="duplicate-flag">같은 문의가 있어요</span>':''}<div><div class="report-meta"><span class="category">${r.category}</span><span class="date">${r.date}</span></div><h3>${r.title}</h3><p>${r.content}</p><span class="location">⌖ ${r.place}</span></div><button class="vote ${r.voted?'voted':''}" data-id="${r.id}">♡ ${r.votes}</button></article>`).join('');
  document.querySelector('#reportCount').textContent = 124 + reports.length; document.querySelector('#voteCount').textContent = reports.reduce((a,r)=>a+r.votes, 1419).toLocaleString();
  const cats = ['급식','시설','학습','안전','생활']; const max = Math.max(...cats.map(c=>reports.filter(r=>r.category===c).length),1); document.querySelector('#categoryBars').innerHTML = cats.map(c=>{const n=reports.filter(r=>r.category===c).length;return `<div class="bar-row"><span>${c}</span><div class="bar"><i style="width:${Math.max(8,n/max*100)}%"></i></div><b>${n}</b></div>`}).join('');
}
function analyze(){ const text = `${els.title.value} ${els.content.value}`.trim(); if(!text){els.analysis.innerHTML='<span class="sparkle">✦</span><div><strong>AI 분류를 기다리고 있어요</strong><p>내용을 입력하면 알맞은 카테고리를 추천해 드릴게요.</p></div>';return} const c=categorize(text); const same=reports.filter(r=>r.category===c&&text.split(/\s+/).some(w=>w.length>2&&r.title.includes(w))).length; els.analysis.innerHTML=`<span class="sparkle">✦</span><div><strong>AI 추천 카테고리: ${c}</strong><p>${same?`비슷한 제보가 ${same}건 있어요. 함께 공감하면 해결이 빨라져요.`:'내용을 분석했어요. 제보 등록 후 담당 부서에 전달됩니다.'}</p></div>`; }
els.filters.addEventListener('click',e=>{if(!e.target.matches('.filter'))return; document.querySelector('.filter.active').classList.remove('active');e.target.classList.add('active');filter=e.target.dataset.category;render()});
els.list.addEventListener('click',e=>{const b=e.target.closest('.vote');if(!b)return;const r=reports.find(x=>x.id===+b.dataset.id);r.voted=!r.voted;r.votes+=r.voted?1:-1;render()});
document.querySelector('#sortButton').addEventListener('click',e=>{newestFirst=!newestFirst;e.currentTarget.innerHTML=newestFirst?'최신순 <span>⌄</span>':'공감순 <span>⌄</span>';render()});
els.title.addEventListener('input',analyze);els.content.addEventListener('input',analyze);els.photo.addEventListener('change',()=>els.fileName.textContent=els.photo.files[0]?.name||'선택 안 함');
els.form.addEventListener('submit',e=>{e.preventDefault();const cat=categorize(`${els.title.value} ${els.content.value}`);reports.unshift({id:nextId++,category:cat,title:els.title.value,content:els.content.value,place:'장소 미입력',date:'방금 전',votes:0,duplicate:false});filter='전체';document.querySelector('.filter.active').classList.remove('active');document.querySelector('[data-category="전체"]').classList.add('active');els.form.reset();els.fileName.textContent='선택 안 함';analyze();render();els.toast.textContent=`제보가 등록되었어요. AI가 '${cat}' 카테고리로 분류했습니다.`;els.toast.classList.add('show');setTimeout(()=>els.toast.classList.remove('show'),3500);location.hash='feed'});
render();
